# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: gbernard <gbernard@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/04/07 19:26:59 by gbernard          #+#    #+#              #
#    Updated: 2016/04/10 13:40:45 by gbernard         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

RESULT = 	a.out
SOURCES =	Board.mli	\
			Board.ml	\
			main.ml
OCAMLMAKEFILE = OCamlMakefile
include $(OCAMLMAKEFILE)
